apiVersion: v1 
kind: Pod 
metadata: 
  name: lab-2 
  labels: 
    app: myapp 
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo (cat /etc/config/myValue) && sleep 3600"]
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: my-config-map
